### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by MarzaElise** [TheGenocides/holybooks#5]
There are a lot of spelling issues. 
- Holybooks -> Holybooks
Fix this and change hollybooks to Holybooks cos it looks weird af dud

**Comment by Genoinno** [comment]
I already did that yesterday and the rest i will check. Thanks!

**Comment by MarzaElise** [comment]
Rerwrite the README.md file and rename the Hollybooks folder

**Comment by Genoinno** [comment]
Alright. It took me a day to check all spelling and other mistype. Would you please check the files again or README.md if there's a typo etc. Thanks for opened an issue

**Comment by Genoinno** [comment]
I'm gonna close this issue :+1: :partying_face:
